Dev
th8ta/arconnect-web-new pull request #1
Opened 2021-10-22 01:12 UTC by codingknite

2021-11-02 00:11 UTC, codingknite commented
@t8 x @maximousblk please don't hold back any feedback.
Thanks :)

2021-11-02 02:26 UTC, t8 commented
Hey @codingknite, would you mind fixing this build issue in Vercel before we move forward here? 
![image](https://user-images.githubusercontent.com/20846869/139776707-4a6fb759-667f-4375-952b-c48f7597b47b.png)

2021-11-02 06:07 UTC, maximousblk commented
fixed

2021-11-02 06:08 UTC, maximousblk commented
@codingknite most of the images are invisible 🤔

2021-11-02 07:55 UTC, codingknite commented
> @codingknite most of the images are invisible 🤔

@maximousblk this is very weird behavior that seems to be with Chrome.
Images render fine in firefox. Chrome shows they exist on the page, they just don't render 🤔

2021-11-02 08:35 UTC, maximousblk commented
#### 📝 Changed routes:


| [**/**](https://arconnect-web-new-l8goymcpd-th8ta.vercel.app/) | [**/onboarding/choose-action**](https://arconnect-web-new-l8goymcpd-th8ta.vercel.app/onboarding/choose-action) |
|:-:|:-:|
|<a href="https://arconnect-web-new-l8goymcpd-th8ta.vercel.app/"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/N8C08vY5qDie5-yAQHFKIqGkZUDCDTtpIU_n0i6v3LoHd-16BEW1ipexjF_6_U_1l9tEc3UyYQaQQxZ2Xc3xhQ.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/f_s_rhvqO3MvlzwU5btJSiOIWo62lSM5jJWq4oO5p51wLewUtvWmUxtKM5krDhCSiNA0HXjz4KlAsHUzw2JU_w.png">(view full size)</a> |<a href="https://arconnect-web-new-l8goymcpd-th8ta.vercel.app/onboarding/choose-action"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/MjrAWPycpLxKkTqtjji2R1-zwx_xI-5zir1Mi18fc4I_dnm8bJM5Z2M314DisTjo4F0V4RaylYCAUqJ-g4NDxw.png&w=600" alt="Screenshot of /onboarding/choose-action" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/_tBndYDw4aGi3avr-nXzBwMtHyAanriS02jUeSymI7tjW16XyUyrpqcQdsk6qNJnHhlWTAZf8wQfH6lWj6Nt9A.png">(view full size)</a> |



| [**/onboarding/explore**](https://arconnect-web-new-l8goymcpd-th8ta.vercel.app/onboarding/explore) | [**/onboarding/guide**](https://arconnect-web-new-l8goymcpd-th8ta.vercel.app/onboarding/guide) |
|:-:|:-:|
|<a href="https://arconnect-web-new-l8goymcpd-th8ta.vercel.app/onboarding/explore"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/-gOJA58sg6K7R-1lnSgxzIJd6H5Ktf5CF-rufeR3IHL0GQV94IHs4w8CQw4r8d0mhrr4Hwx9m17wE_VDBWmeGg.png&w=600" alt="Screenshot of /onboarding/explore" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/nra8yuOnbNY6DuIRso3wdmVLFg84oLm61uf3uxcxv88kZzC5bFFUBzY4Qf_ZXHNIDoojyU4p2OiZ32mcNnKgMQ.png">(view full size)</a> |<a href="https://arconnect-web-new-l8goymcpd-th8ta.vercel.app/onboarding/guide"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/bN1GjPYNDlYnjW1-MOwRkxMfF5BsBKPWXjxyQdrc2iqLdb7mbsVPfnTRvpIQekaZF8gvhm1ALNFiYiRkiP3rpg.png&w=600" alt="Screenshot of /onboarding/guide" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/RbsCUVwrqM8mF7VjC_2ZFheh4N6Xxxcc_73YRMnlNqT2M3koyf0dEJ-rYqD4HNCVqq4U8Y7rngU9vD__QsK7tA.png">(view full size)</a> |



| [**/onboarding**](https://arconnect-web-new-l8goymcpd-th8ta.vercel.app/onboarding) |
|:-:|
|<a href="https://arconnect-web-new-l8goymcpd-th8ta.vercel.app/onboarding"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/C-fDTSLq5vhfIax3wEhHz4F1jdZnLCUuuUAPikCftOQy3cWlSzEoBcqdkKRTVK2xa48E_jMBRr4V2HNEusNGOQ.png&w=600" alt="Screenshot of /onboarding" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/I5PyTZjJPpjWbiWgU8Dg8Jc5u3lkrYULPaJluJVrGw1MG4SGlz9CVf2YBb5EGyWRydjv3Oh4bVMZW3X61wuN8w.png">(view full size)</a> |







Commit 8b3ab817a92e9edba7ee1c59d9ab849cb2c51433 (https://arconnect-web-new-l8goymcpd-th8ta.vercel.app).

2021-11-02 12:37 UTC, codingknite commented
## Todo

This commit was supposed to fix all the images but some still remain stubborn. 

- [ ] Fix images
- [ ] Add micro interactions to buttons

✔️ ready to merge

2021-11-02 18:40 UTC, t8 commented
@codingknite have added some comments on a new Jam.dev board. Let me know if you can't see this :)

https://jam.dev/tates-team/browser/list

2021-11-02 19:29 UTC, codingknite commented
Thanks @t8 saw all the comments. We had an issue with the svgs in the figma file which led to the weird behavior with all the images. Max helped figure this out so we've made those changes. 
Thanks again for the feedback here 👍

2021-11-03 00:35 UTC, codingknite commented
Not sure why the images are shrinking in production.

### development
![shot2](https://user-images.githubusercontent.com/70036189/139969952-595a3540-87c6-4c77-af60-710d60c2ba70.png)

### production
![shot](https://user-images.githubusercontent.com/70036189/139969919-35a3db7b-9506-4ffa-9873-2d0843bce2a8.png)


@t8 x @maximousblk do you think this could have anything to do with CSS Grid

2021-11-04 01:46 UTC, codingknite commented
@t8 just made some major fixes here.

2021-11-10 04:34 UTC, t8 requested changes
Partial review. Final half coming tomorrow. You can commit most of these suggestions directly :)

2021-11-10 04:34 UTC, t8 commented on components/Home/Features/index.tsx
> +            <Link href="/security">
```suggestion
            <Link href="https://docs.th8ta.org/arconnect/functions">
```

2021-11-10 04:34 UTC, t8 commented on components/Home/Features/index.tsx
> +          text="ArConnect is your go to forum to access Dapps and learn about the permaweb ecosystem."
```suggestion
          text="ArConnect is your go-to solution to access Dapps while learning about the permaweb ecosystem."
```

2021-11-10 04:34 UTC, t8 commented on components/Home/Features/index.tsx
> +          text="With ArConnect's user-friendly interface, you can manage your Arweave balance, view and transfer assets and see your latest transactions. The extension allows you to add all your wall
```suggestion
          text="With ArConnect's user-friendly interface, you can manage your Arweave balance, view and transfer assets, and see your latest transactions. The extension allows you to add all your wallets and switch between them easily."
```

2021-11-10 04:34 UTC, t8 commented on components/Home/Features/index.tsx
> +              Built by Developers for Developers, ArConnect allows you use
```suggestion
              Built by devs for devs, ArConnect allows you to use
```

2021-11-10 04:34 UTC, t8 commented on components/Home/Features/index.tsx
> +              developer friendly tools to integrate and build on ArConnect
```suggestion
              developer-friendly tools to integrate and build on ArConnect
```

2021-11-10 04:34 UTC, t8 commented on components/Home/Features/index.tsx
> +              across blockchains seamlessly. Explore our Developer documentation
```suggestion
             seamlessly. Explore our developer documentation
```

2021-11-10 04:34 UTC, t8 commented on components/Home/Features/index.tsx
> +            <h3>Permanent Security</h3>
```suggestion
            <h3>Top-notch Security</h3>
```

2021-11-10 04:34 UTC, t8 commented on components/Home/Features/index.tsx
> +              With ArConnect&apos;s user-friendly interface, you can manage your
This paragraph should be changed to:

```
ArConnect features a robust permissions system, application allowances, and the ability to easily track all ArConnected activity through Dapps.
```

2021-11-10 04:34 UTC, t8 commented on components/Home/Features/index.tsx
> +            <Link href="/docs">
This button should be disabled

2021-11-10 04:34 UTC, t8 commented on components/Home/Features/index.tsx
> +              <a className={styles.docsBtn}>Learn more</a>
```suggestion
              <a className={styles.docsBtn}>Learn more (coming soon)</a>
```

2021-11-10 04:34 UTC, t8 commented on components/Home/FAQ/index.tsx
> +          10,000+ people <span>and counting</span> love ArConnect
```suggestion
          15,000+ people <span>and counting</span> love ArConnect
```

2021-11-10 04:34 UTC, t8 commented on components/Home/FAQ/index.tsx
> +        <section>
## Need to figure out before merging

2021-11-10 04:34 UTC, t8 commented on components/Home/FAQ/index.tsx
> +            ArConnect is a completely decentralized network built on top of the
This information is wrong. Need to reword. 

```
Feel free to connect with us on Discord, Twitter, or GitHub!
```

2021-11-10 04:34 UTC, t8 commented on pages/onboarding/index.tsx
> +      text="ArConnect was tailor made for you regardless of your background,
```suggestion
      text="ArConnect was tailor-made for you regardless of your background,
```

2021-11-10 04:34 UTC, t8 commented on pages/onboarding/index.tsx
> +      skill or experience, it’s unbreakable, yet malleable. Please select
```suggestion
      skills or experience; it’s unbreakable, yet malleable. Please select
```

2021-11-10 04:34 UTC, t8 commented on pages/onboarding/index.tsx
> +      what best describes you"
```suggestion
      what best describes you."
```

2021-11-10 04:34 UTC, t8 commented on pages/onboarding/guide.tsx
> +          crypto, But we understand that you probably need ArConnect for
```suggestion
          crypto, but we understand that you may need ArConnect for
```

2021-11-10 04:34 UTC, t8 commented on pages/onboarding/guide.tsx
> +          something immediately
```suggestion
          something immediately...
```

2021-11-10 04:34 UTC, t8 commented on components/Explore/index.tsx
> +        introParagraph="Please click the <span>Download</span> button on this page to get ArConnect for your
```suggestion
        introParagraph="Please click the <span>Install ArConnect</span> button on this page to get ArConnect for your
```

2021-11-10 04:34 UTC, t8 commented on components/Explore/index.tsx
> +        browser if you haven’t already, If you have then let’s proceed! You
```suggestion
        browser if you haven’t already. If you have then let’s proceed!
```

2021-11-10 04:34 UTC, t8 commented on components/Explore/index.tsx
> +        basically just have to complete the following actions below step by step"
```suggestion
        Complete the following actions step-by-step."
```

2021-11-10 04:34 UTC, t8 commented on components/Explore/index.tsx
> +        introParagraph="Please click the <span>Download</span> button on this page to get ArConnect for your browser if you haven’t already, If you have then let’s proceed!
```suggestion
        introParagraph="Please click the <span>Install ArConnect</span> button on this page to get ArConnect for your browser if you haven’t already. If you have then let’s proceed!```

2021-11-16 17:04 UTC, t8 approved these changes
LGTM. Amazing work @codingknite! Merge at will.
![image](https://c.tenor.com/KeSDB2EZjPAAAAAM/leonardo-di-caprio-wolf-of-wall-street.gif)

2021-11-18 11:42 UTC, merged